In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf

c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c

In [2]:
#reading data from the CSV
dataset = pd.read_csv('financial-intermediary-funds-funding-decisions.csv')
print(dataset.shape)
dataset = dataset.drop(['As of Date','Calendar Year'], axis = 1)
dataset = dataset.fillna(value = 'None')

(16128, 11)


In [3]:
#Now select features from the dataset
X = dataset.iloc[:,1:]
X = X.drop(['Financial Product'], axis= 1)
X = X.values
print(X.shape)

(16128, 7)


In [4]:
#now seleting the dependent variable
Y = dataset.iloc[:, 8:9].values
lblEncd_result = LabelEncoder()
Y = lblEncd_result.fit_transform(Y)

c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
#Encode the string data into number
lblEncd_X0 = LabelEncoder()
X[:,0] = lblEncd_X0.fit_transform(X[:,0])

In [6]:
lblEncd_X1 = LabelEncoder()
X[:,1] = lblEncd_X1.fit_transform(X[:,1])

In [7]:
lblEncd_X2 = LabelEncoder()
X[:,2] = lblEncd_X2.fit_transform(X[:,2]) 

In [8]:
lblEncd_X3 = LabelEncoder()
X[:,3] = lblEncd_X3.fit_transform(X[:,3])

In [9]:
lblEncd_X4 = LabelEncoder()
X[:,4] = lblEncd_X4.fit_transform(X[:,4])

In [10]:
lblEncd_X5 = LabelEncoder()
X[:,5] = lblEncd_X5.fit_transform(X[:,5])

In [11]:
lblEncd_X6 = LabelEncoder()
X[:,6] = lblEncd_X6.fit_transform(X[:,6])

In [12]:
onehotencoder = OneHotEncoder(categorical_features= [0,1,2,3,4,6])
X = onehotencoder.fit_transform(X).toarray()

c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
print(X)

[[0.000e+00 0.000e+00 1.000e+00 ... 0.000e+00 0.000e+00 1.295e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 3.790e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 9.420e+02]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 4.300e+01]
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 1.110e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 7.888e+03]]


In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)

[[-0.2532099  -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
  -1.36854612]
 [-0.2532099  -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
   0.79421029]
 [-0.2532099  -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
   0.71102735]
 ...
 [ 3.94929266 -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
  -1.12883174]
 [-0.2532099  -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
   0.12833701]
 [-0.2532099  -0.02690656 -0.35979191 ... -0.05190665 -0.06442903
   1.30560097]]


In [15]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(16, activation='relu'),
  tf.keras.layers.Dropout(0.1),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.1),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.1),
  tf.keras.layers.Dense(8, activation='softmax')
])

W0825 23:22:38.138218  5096 deprecation.py:506] From c:\users\vimesh shah\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [16]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.fit(X_train, Y_train, epochs=5)

Epoch 1/5
9676/9676 [==============================] - 1s 134us/sample - loss: 0.4551 - acc: 0.8578
Epoch 2/5
9676/9676 [==============================] - 1s 98us/sample - loss: 0.0816 - acc: 0.9752
Epoch 3/5
9676/9676 [==============================] - 1s 96us/sample - loss: 0.0403 - acc: 0.9859
Epoch 4/5
9676/9676 [==============================] - 1s 97us/sample - loss: 0.0307 - acc: 0.9895
Epoch 5/5
9676/9676 [==============================] - 1s 97us/sample - loss: 0.0249 - acc: 0.9914


In [18]:
model.evaluate(X_test, Y_test)

6452/6452 [==============================] - 0s 64us/sample - loss: 0.0368 - acc: 0.9921


[0.036789355292922966, 0.9920955]

In [19]:
a = model.predict([X_test])

In [20]:
np.argmax(a[50])

3

In [21]:
Y_test[50]

3